CREATE TABLE ORDERS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    STATUS ENUM('SUCCESS' , 'PENDING' , 'CANCELLED') DEFAULT 'PENDING' ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)