CREATE TABLE ORDER_ITEMS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    ORDER_ID BIGINT ,
    QUANTITY INT ,
    PER_UNIT_PRICE DOUBLE ,
    TOTAL_PRICE DOUBLE ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,

    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
)